### ISSUE TITLE
Add functionality to allow the item creator to edit the passport

### ISSUE THREAD

**Issue by fabianzeiher** [cetceeve/ItemBlocks#6]
We want to allow the creator of an item (the first owner of the nft) to be able to edit the properties of the item passport.

- [x] add creator property to contract
- [x] check creator of contract on edit page

**Comment by sifisKoen** [comment]
We solved this issue creating a hash-map where we keep all item owners in an array `{item : [users]}`. So then we created a function `isEligible` that it checks if the **user** is eligible for changes. Explanation:

```solidity
if (userAddress == ownerOf(tokenID) || userAddress == allItemOwners[tokenId][0]) return true;
```

We make a check if the user is the first user in the array of the hash-map for the current item, if it's true that means the user is the creator of the item because when the user creates an item they get added as first user in the hash-map array.
